# Generated by Django 3.2.3 on 2021-09-23 15:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userinput',
            options={'ordering': [django.db.models.expressions.OrderBy(django.db.models.expressions.F('number'), descending=True, nulls_last=True)]},
        ),
        migrations.AlterField(
            model_name='userinput',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
