# Generated by Django 3.2.3 on 2021-09-24 10:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_userinput_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinput',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 24, 10, 23, 50, 366979, tzinfo=utc)),
        ),
    ]
