# Generated by Django 3.2.3 on 2021-09-24 14:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0008_alter_userinput_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinput',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_inputs', to=settings.AUTH_USER_MODEL),
        ),
    ]
