# Generated by Django 3.2.3 on 2021-09-25 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_userinput_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userinput',
            options={'ordering': ['created_at']},
        ),
    ]
